# language target
language: python
os: linux
dist: bionic
sudo: required
python:
  - "3.7"


# install dependencies depending on the particular OS
install:
  - sudo pip install PyInstaller

# build & test scripts
script:
  - sudo pip3 install .
  - PyInstaller nanovna-saver.py
  - cd dist && ls -lh
  # mv skyflash-gui skyflash && gzip skyflash
  # mv dist/skyflash.gz final/
    # ls -lh final/

# notifications (only via telegram)
notifications:
  email: true

# make the apps for each OS
before_deploy:
- export VERSION="$(git describe --tags --exact-match HEAD 2> /dev/null)"
- ./travis/before_deploy.sh ${TARGETOS} ${VERSION}
- ls -l ./final/

# deploy to Github
# deploy:
#   # deploy on linux
#   - provider: releases
#     api_key: $OAUTH
#     file_glob: true
#     draft: true
#     overwrite: true
#     skip_cleanup: true
#     on:
#       tags: true
#     file:
#       - "final/*"

